### ISSUE TITLE
MEF: OCV Backend for Proposal Consideration

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/mina-on-chain-voting#28]
- [x] Backend architecture
- [x] Eligibility check
- [x] Proposal Consideration 
- [x] Integration with proposal system
- [x] Testing and debugging

Developer: https://github.com/leomanza

**Comment by CristinaEche** [comment]
From Daily meetings:

- [ ] Provide specification on how to implement voting with OCV

**Comment by CristinaEche** [comment]
connected with: https://github.com/MinaFoundation/pgt-web-app/issues/64

**Comment by CristinaEche** [comment]
- [ ] for this testing we need at least 2 votes to move the proposal to deliberation

**Comment by remigiusz-antczak** [comment]
This one seems to be completed, I'm only unsure if there's a specification on how to implement voting with OCV. @leomanza please let me know if it's available in the OCV repository

**Comment by remigiusz-antczak** [comment]
I think it's enough, thank you! I'm completing this one then
